### ISSUE TITLE
OTA with ESP-01

### ISSUE THREAD

**Issue by saaivignesh20-zz** [csnol/1CHIP-Programmers#2]
Can I just do the OTA to STM32 with some modifications using the ESP-01. I am afraid I can't because it only has 8 pins in total.

**Comment by csnol** [comment]
Of course you can!
Please move to my next repo

https://github.com/csnol/STM32-OTA

It’s only use 4 GPIOs  
Try below:
GPIO0 - NRST
GPIO2 - ROOT0
RXD - TXD
TXD - RXD

**Comment by saaivignesh20-zz** [comment]
Thanks a lot!
